### ISSUE TITLE
Стандартний метод рядка

### ISSUE THREAD

**Issue by AlexNyzovyi** [ivan-masiuk/geekHub1#3]
https://github.com/ivan-masiuk/geekHub1/blob/cb7b7cdf44acad58b61a019958b91347cbb35e1e/HT_2/task6.py#L15

Є прекрасний метод `'somestr'.isdigit()` - спробуй погратись. Основні методи треба знати.

**Comment by ivan-masiuk** [comment]
Привіт, так вона ж не працює, якщо просто текст без пробілів. А наші тицьки
не містять пробілів :)
Наприклад якщо
S = input()
print(S.isdigit())

//klghj9823
//False

//65746578
//True
Я, мабуть, не дуже зрозумів як правильно користуватись нею
Попередні факапи виправив, залью через 2 хв на Гіт

чт, 12 нояб. 2020 г. в 01:38, AlexNyzovyi <notifications@github.com>:

**Comment by AlexNyzovyi** [comment]
:) Зверни увагу, який рядок я виділив і яку перевірку в ньому ти робиш - і все встане на свої місця.

**Comment by ivan-masiuk** [comment]
Аааа, точняк)))
Я просто в Гіті на рівні равлика розбираюсь поки що
Зара виправлю)

чт, 12 нояб. 2020 г., 10:03 AlexNyzovyi <notifications@github.com>:
